//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEPe.DataAccessModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public Consulta()
        {
            this.Agenda = new HashSet<Agenda>();
            this.ConsultaMedicamento = new HashSet<ConsultaMedicamento>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
        public int Profissional_Id { get; set; }
    
        public virtual ICollection<Agenda> Agenda { get; set; }
        public virtual ICollection<ConsultaMedicamento> ConsultaMedicamento { get; set; }
        public virtual Profissional Profissional { get; set; }
    }
}
