//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEPe.DataAccessModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PEPeEntities : DbContext
    {
        public PEPeEntities()
            : base("name=PEPeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Agenda> Agenda { get; set; }
        public DbSet<Consulta> Consulta { get; set; }
        public DbSet<ConsultaMedicamento> ConsultaMedicamento { get; set; }
        public DbSet<Exame> Exame { get; set; }
        public DbSet<Medicamento> Medicamento { get; set; }
        public DbSet<Profissional> Profissional { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
